# Generated by Django 3.2 on 2022-03-03 10:59

from django.conf import settings
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('phone_number', models.CharField(max_length=11, validators=[user.models.MobileNumberValidator()])),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(default='', error_messages={'unique': 'A user with that Phone number already exists.'}, help_text='Example : 09125573688', max_length=11, unique=True, validators=[user.models.MobileNumberValidator()], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='users',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), user.models.username_validation], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='users',
            name='verification',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email')], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('birth_date1', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('other_email', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator()])),
                ('phone_number1', models.CharField(blank=True, max_length=11, null=True, validators=[user.models.MobileNumberValidator()], verbose_name='phone number')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_email_in_website', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'email')},
            },
        ),
    ]
